### ISSUE TITLE
JavaScript

### ISSUE THREAD

**Issue by Lowry-Alcaraz** [Lowry-Alcaraz/Prework-Study-Guide#4]
# JavaScript

As a boot camp student
I want the prework notes to be structured on a webpage
So that I can easily find and read the information

GIVEN a Prework Study Guide website
WHEN I view the study guide
THEN I can see the four topics I learned listed along with a suggestion on what I should study first

**Comment by joaomarcosjova** [comment]
To structure the Prework Study Guide webpage, you can follow these steps:

Outline Content: Define the main topics you want to cover in the Prework Study Guide. For example:

Introduction to JavaScript
Variables and Data Types
Control Flow and Loops
Functions and Scope
Create HTML Skeleton: Write the HTML structure to organize the content. You can use headings, paragraphs, lists, etc., to present the information.

Add Content: Populate the HTML elements with the content related to each topic. This could include explanations, examples, exercises, and references.

Apply Basic Styling: Optionally, add minimal CSS to enhance the visual presentation of the content. You can adjust fonts, colors, margins, and padding as needed.

First, let's create the HTML file (`index.html`):

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Prework Study Guide</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <header>
        <h1>Prework Study Guide</h1>
    </header>
    <main>
        <section id="introduction">
            <h2>Introduction to JavaScript</h2>
            <p>Basic concepts, history, and purpose of JavaScript.</p>
        </section>
        <section id="variables">
            <h2>Variables and Data Types</h2>
            <p>Learn about variables, strings, numbers, booleans, and more.</p>
        </section>
        <section id="control-flow">
            <h2>Control Flow and Loops</h2>
            <p>Understand decision-making with if statements, loops like for and while, and more.</p>
        </section>
        <section id="functions">
            <h2>Functions and Scope</h2>
            <p>Dive into functions, parameters, return values, and scope in JavaScript.</p>
        </section>
    </main>
    <footer>
        <p>&copy; 2024 Prework Study Guide</p>
    </footer>
</body>
</html>
```

Next, let's create the CSS file (`styles.css`):

```css
body {
    font-family: Arial, sans-serif;
    margin: 0;
    padding: 0;
    background-color: #f2f2f2;
    color: #333;
}

header, footer {
    background-color: #007bff;
    color: #fff;
    text-align: center;
    padding: 10px;
}

h1 {
    margin: 0;
}

main {
    max-width: 800px;
    margin: 20px auto;
    padding: 20px;
    background-color: #fff;
    border-radius: 8px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
}

section {
    margin-bottom: 20px;
}

h2 {
    color: #007bff;
}

footer {
    position: fixed;
    bottom: 0;
    width: 100%;
}
```

This structure separates the content (HTML), presentation (CSS), and potentially behavior (JavaScript) into distinct files, making the code clean and modular. You can further extend and customize each section of the study guide by adding more content and styling rules as needed.
